Added Devise Controller
IIC3745-Grupo-5/ProyectoB pull request #10
Opened 2021-11-26 00:49 UTC by Meaylwin

## What?
Added CRUD of Users session
Added button to register and login 
And added the logout when click back in cinema_show

## Why?
It's needed

## Tests?
NONE

## Screenshots
![image](https://user-images.githubusercontent.com/14930275/143511248-d52cef5a-3237-47f1-a6db-183f3bf5e0e3.png)

2021-11-26 03:36 UTC, dasolari requested changes
Deje hartos comentarios, pero super bien que se haya agregado esta funcionalidad.

2021-11-26 03:36 UTC, dasolari commented on app/views/cinemas/index.html.erb
>  </section>
Igual la idea era que esta página mostrara una lista de cines (solo hay uno, pero en el caso de que se quieran agregar más), por lo que no usaría esta vista para login, sino que crearía una vista especial para login y que al hacer un login exitoso me redirija a la lista de cines.

2021-11-26 03:36 UTC, dasolari commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
Por qué se agregó esto?

2021-11-26 03:36 UTC, dasolari commented on config/routes.rb
>  Rails.application.routes.draw do
Siguiendo un comentario que dije antes, haría que el root path sea ahora la nueva vista de login.

2021-11-26 03:36 UTC, dasolari commented on db/migrate/20211125202732_devise_create_users.rb
> +      # t.datetime :locked_at
Borraría todos estos comentarios autogenerados.

2021-11-26 03:36 UTC, dasolari commented on db/migrate/20211125202732_devise_create_users.rb
> +    # add_index :users, :unlock_token,         unique: true
Idem.

2021-11-26 03:36 UTC, dasolari commented on spec/cinemas_spec.rb
> +      click_link 'Logout'
Siguiendo con la lógica de arriba, este test lo modificaría para que se pueda hacer login y luego mantener la lógica que tenía, pero además crearía un test aparte para el login y el registro.

2021-11-26 03:36 UTC, dasolari commented on test/fixtures/users.yml
> +# column: value
Borraría este archivo dado que no estamos usando tests unitarios sino que solo spec con capybara.

2021-11-26 03:36 UTC, dasolari commented on test/models/user_test.rb
> +end
Idem, borraría la carpeta de test generada por devise.

2021-11-26 13:11 UTC, Meaylwin commented on app/views/cinemas/index.html.erb
>  </section>
Perfecto!

2021-11-26 13:15 UTC, Meaylwin commented on spec/cinemas_spec.rb
> +      click_link 'Logout'
Perfect!

2021-11-26 13:36 UTC, Meaylwin commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
Es innecesaria. Eliminada

2021-11-27 04:53 UTC, dasolari approved these changes
👍

2021-11-27 04:53 UTC, merged